version: '2'
services:
    coredns-intra:
        image: coredns/coredns:latest
        restart: always
        entrypoint:
            - /coredns
            - -conf
            - /etc/coredns/Corefile
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - '../conf/intra:/etc/coredns'
#    coredns-dev:
#        image: coredns/coredns:latest
#        restart: always
#        entrypoint:
#            - /coredns
#            - -conf
#            - /etc/coredns/Corefile
#        ports:
#            - '53:53'
#            - '53:53/udp'
#        volumes:
#            - '../conf/dev:/etc/coredns'
    api:
        image: python:3-alpine
        restart: always
        volumes:
            - '../src/server:/api'
            - '../conf:/api/conf'
